### ISSUE TITLE
Support for transposing instruments

### ISSUE THREAD

**Issue by virusys** [venturemedia/mxml#4]
Hi there,
I already asked about this in the musickit project, but maybe it's a more relevant issue for mxml.

I wanted to know if there was support for the <transpose> tags in MusicXML files, so I can display a score differently depending on what instrument is used. 

If not, would you be able to point me in the right direction in implementing this feature myself?

Thanks again for your work!

**Comment by aleph7** [comment]
Sounds like you would have to keep track of the transpose and modify the pitches. Sorry for not being much help, it's been a while since I looked at the code.

**Comment by virusys** [comment]
No worries, thank you for getting back to me!

I have done it this way and have it nearly working— going through each note and transposing it manually with a helper method that I made. However I'm having problems setting the overall key of the score. I'm doing it like this:

```c++
    for (auto& part : _score->parts()) {

        for (std::size_t measureIndex = 0; measureIndex < part->measures().size(); measureIndex += 1) {
            Measure& measure = *part->measures().at(measureIndex);

			//set the key
			if (measureIndex == 0) {
				auto attributes = std::unique_ptr<dom::Attributes>(new dom::Attributes{});

				std::unique_ptr<dom::Key> newKey = std::unique_ptr<dom::Key>(new dom::Key{});

				NSLog(@"transposition: setting to circle of fifths: %d", [self transpositionToFifths]);

				newKey->setFifths([self transpositionToFifths]);
				attributes->setKey(1, std::unique_ptr<dom::Key>(new dom::Key(*newKey)));
				attributes->setParent(&measure);
				measure.addNode(std::move(attributes));
			}

            for (auto& node : measure.nodes()) {
                if (TimedNode* timedNode = dynamic_cast<TimedNode*>(node.get())) {
                    if (Chord* chord = dynamic_cast<Chord*>(timedNode)) {
                        for (auto& note : chord->notes()) {
							//transpose note
                            note->pitch = transposePitch(std::unique_ptr<dom::Pitch>(new dom::Pitch(note->pitch->step(), note->pitch->alter(), note->pitch->octave())), [[[NSUserDefaults standardUserDefaults] objectForKey:@"current_transposition"] floatValue]);
                        }
                    }
                }
            }
        }
    }
```

With the above code the key change appears right before the beginning of the second measure, instead of at the beginning of the score. I tried setting the parameter to the `score` pointer instead of the first measure in this line:

```c++
attributes->setParent(&measure);
```

Except it's giving me this error: 
`Cannot initialize a parameter of type 'const mxml::dom::Node *' with an rvalue of type 'std::unique_ptr<mxml::dom::Score> *'`

I'm sure I will figure this out eventually, I'm just a bit rusty with C++ (usually work with Objc and swift here). If you see anything obvious that I'm missing, let me know 👍 

Thanks again!

**Comment by virusys** [comment]
I figured it out — what I was doing before was adding additional attributes tags to the measure instead of editing the existing ones. I solved this issue using this code:

```objc
for (auto & node : measure.nodes()) {
     if (Attributes* attributes = dynamic_cast<Attributes*>(node.get())) {
          attributes->setKey(1, std::unique_ptr<dom::Key>(new dom::Key(*newKey)));

          if ([[[NSUserDefaults standardUserDefaults] objectForKey:@"bassClef"] boolValue]) {
               std::unique_ptr<dom::Clef> bassClef = std::unique_ptr<dom::Clef>(new dom::Clef{});
               bassClef->setSign(presentOptional(Clef::Sign::F));
               attributes->setClef(1, std::unique_ptr<dom::Clef>(new dom::Clef(*bassClef)));
          }
     }
}
```
